build:
    verbosity: detailed

image: Visual Studio 2017

install:
  - ps: Install-Product node 8 x64

build_script:
    - cmd: yarn
    - cmd: cd src/Docs
    - cmd: dotnet restore
    - cmd: dotnet fable webpack -- -p

cache:
  - "%LOCALAPPDATA%\\Yarn"
